"""your message

Revision ID: 36c4d20172c2
Revises: 802066acdda6
Create Date: 2024-10-23 23:48:32.513180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c4d20172c2'
down_revision = '802066acdda6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
